# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06servod\"$\n\x0e\x43onnectRequest\x12\x12\n\nboard_name\x18\x01 \x01(\t\"S\n\x0f\x43onnectResponse\x12\x14\n\x0c\x63pu_uart_pty\x18\x01 \x01(\t\x12\x15\n\rcr50_uart_pty\x18\x02 \x01(\t\x12\x13\n\x0b\x65\x63_uart_pty\x18\x03 \x01(\t2F\n\x06Servod\x12<\n\x07\x43onnect\x12\x16.servod.ConnectRequest\x1a\x17.servod.ConnectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTREQUEST']._serialized_start=25
  _globals['_CONNECTREQUEST']._serialized_end=61
  _globals['_CONNECTRESPONSE']._serialized_start=63
  _globals['_CONNECTRESPONSE']._serialized_end=146
  _globals['_SERVOD']._serialized_start=148
  _globals['_SERVOD']._serialized_end=218
# @@protoc_insertion_point(module_scope)
